//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        internal static string ChatWindow_AddMember {
            get {
                return ResourceManager.GetString("ChatWindow_AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invited person should visit the following web address.
        /// </summary>
        internal static string ChatWindow_AddMember_Instructions {
            get {
                return ResourceManager.GetString("ChatWindow_AddMember_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users PIN.
        /// </summary>
        internal static string ChatWindow_AddMember_Pin {
            get {
                return ResourceManager.GetString("ChatWindow_AddMember_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Id.
        /// </summary>
        internal static string ChatWindow_ChatId {
            get {
                return ResourceManager.GetString("ChatWindow_ChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ChatWindow_CloseChat {
            get {
                return ResourceManager.GetString("ChatWindow_CloseChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap, to achieve time.
        /// </summary>
        internal static string ChatWindow_ExtendTimeHint {
            get {
                return ResourceManager.GetString("ChatWindow_ExtendTimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat was closed!.
        /// </summary>
        internal static string ChatWindow_Messages_OnClose {
            get {
                return ResourceManager.GetString("ChatWindow_Messages_OnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security level.
        /// </summary>
        internal static string ChatWindow_SecurityLevel {
            get {
                return ResourceManager.GetString("ChatWindow_SecurityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe connection.
        /// </summary>
        internal static string ChatWindow_SecurityLevel_1 {
            get {
                return ResourceManager.GetString("ChatWindow_SecurityLevel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection at risk.
        /// </summary>
        internal static string ChatWindow_SecurityLevel_2 {
            get {
                return ResourceManager.GetString("ChatWindow_SecurityLevel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection UNSAFE - please log off !.
        /// </summary>
        internal static string ChatWindow_SecurityLevel_3 {
            get {
                return ResourceManager.GetString("ChatWindow_SecurityLevel_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded files.
        /// </summary>
        internal static string ChatWindow_UploadedFile {
            get {
                return ResourceManager.GetString("ChatWindow_UploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string ChatWindow_UploadFile {
            get {
                return ResourceManager.GetString("ChatWindow_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string ChatWindow_Users {
            get {
                return ResourceManager.GetString("ChatWindow_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-EN.
        /// </summary>
        internal static string Culture_ {
            get {
                return ResourceManager.GetString("Culture_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join chat.
        /// </summary>
        internal static string FrontPage_Buton_JoinChat {
            get {
                return ResourceManager.GetString("FrontPage_Buton_JoinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat.
        /// </summary>
        internal static string FrontPage_Buton_StartChat {
            get {
                return ResourceManager.GetString("FrontPage_Buton_StartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new chat.
        /// </summary>
        internal static string FrontPage_Instruction_1 {
            get {
                return ResourceManager.GetString("FrontPage_Instruction_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a member.
        /// </summary>
        internal static string FrontPage_Instruction_2 {
            get {
                return ResourceManager.GetString("FrontPage_Instruction_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the PIN and chatroom link to other chat members.
        /// </summary>
        internal static string FrontPage_Instruction_3 {
            get {
                return ResourceManager.GetString("FrontPage_Instruction_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string InitiationWindow_CreateButton {
            get {
                return ResourceManager.GetString("InitiationWindow_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string InitiationWindow_JoinButton {
            get {
                return ResourceManager.GetString("InitiationWindow_JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string InitiationWindow_Name {
            get {
                return ResourceManager.GetString("InitiationWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        internal static string InitiationWindow_Nick {
            get {
                return ResourceManager.GetString("InitiationWindow_Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string InitiationWindow_PIN {
            get {
                return ResourceManager.GetString("InitiationWindow_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Id.
        /// </summary>
        internal static string InitiationWindow_RoomId {
            get {
                return ResourceManager.GetString("InitiationWindow_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite to chat.
        /// </summary>
        internal static string InitiationWindow_TitleJoin {
            get {
                return ResourceManager.GetString("InitiationWindow_TitleJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chat.
        /// </summary>
        internal static string InitiationWindow_TitleNew {
            get {
                return ResourceManager.GetString("InitiationWindow_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string SystemMessages_Anonymous {
            get {
                return ResourceManager.GetString("SystemMessages_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not join the chat.
        /// </summary>
        internal static string SystemMessages_CannotJoin {
            get {
                return ResourceManager.GetString("SystemMessages_CannotJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat was closed.
        /// </summary>
        internal static string SystemMessages_ChatClosed {
            get {
                return ResourceManager.GetString("SystemMessages_ChatClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chatroom with the following web address, does not exist.
        /// </summary>
        internal static string SystemMessages_ChatroomNotExist {
            get {
                return ResourceManager.GetString("SystemMessages_ChatroomNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created a room.
        /// </summary>
        internal static string SystemMessages_CreatedRoom {
            get {
                return ResourceManager.GetString("SystemMessages_CreatedRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tried to delete a file which does not exist.
        /// </summary>
        internal static string SystemMessages_DeleteFileNotExist {
            get {
                return ResourceManager.GetString("SystemMessages_DeleteFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string SystemMessages_FileDeleted_1 {
            get {
                return ResourceManager.GetString("SystemMessages_FileDeleted_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been deleted by.
        /// </summary>
        internal static string SystemMessages_FileDeleted_2 {
            get {
                return ResourceManager.GetString("SystemMessages_FileDeleted_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is to big.
        /// </summary>
        internal static string SystemMessages_FileToBig {
            get {
                return ResourceManager.GetString("SystemMessages_FileToBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added file.
        /// </summary>
        internal static string SystemMessages_FileUploaded_1 {
            get {
                return ResourceManager.GetString("SystemMessages_FileUploaded_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the conversation.
        /// </summary>
        internal static string SystemMessages_FileUploaded_2 {
            get {
                return ResourceManager.GetString("SystemMessages_FileUploaded_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jas joined the chat.
        /// </summary>
        internal static string SystemMessages_HasJoined {
            get {
                return ResourceManager.GetString("SystemMessages_HasJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident list was cleared.
        /// </summary>
        internal static string SystemMessages_IncidentsClear {
            get {
                return ResourceManager.GetString("SystemMessages_IncidentsClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left the building:).
        /// </summary>
        internal static string SystemMessages_LeftBuilding {
            get {
                return ResourceManager.GetString("SystemMessages_LeftBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged off successfully.
        /// </summary>
        internal static string SystemMessages_LoggedOffSuccessfully {
            get {
                return ResourceManager.GetString("SystemMessages_LoggedOffSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new slot. PIN = .
        /// </summary>
        internal static string SystemMessages_NewSlotAdded {
            get {
                return ResourceManager.GetString("SystemMessages_NewSlotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN not found.
        /// </summary>
        internal static string SystemMessages_NoPinFound {
            get {
                return ResourceManager.GetString("SystemMessages_NoPinFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        internal static string SystemMessages_NotAuthorized {
            get {
                return ResourceManager.GetString("SystemMessages_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner nick.
        /// </summary>
        internal static string SystemMessages_OwnerNick {
            get {
                return ResourceManager.GetString("SystemMessages_OwnerNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added owner slot.
        /// </summary>
        internal static string SystemMessages_OwnerSlotAdded {
            get {
                return ResourceManager.GetString("SystemMessages_OwnerSlotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN has been used before.
        /// </summary>
        internal static string SystemMessages_PinUsedBefore {
            get {
                return ResourceManager.GetString("SystemMessages_PinUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room existence time was expanded.
        /// </summary>
        internal static string SystemMessages_RoomExistanceExtended {
            get {
                return ResourceManager.GetString("SystemMessages_RoomExistanceExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find slot.
        /// </summary>
        internal static string SystemMessages_SlotNotFound {
            get {
                return ResourceManager.GetString("SystemMessages_SlotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User matched with this PIN code does not exist.
        /// </summary>
        internal static string SystemMessages_UserPinNotExist {
            get {
                return ResourceManager.GetString("SystemMessages_UserPinNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was kicked.
        /// </summary>
        internal static string SystemMessages_WasKicked {
            get {
                return ResourceManager.GetString("SystemMessages_WasKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in.
        /// </summary>
        internal static string SystemMessages_Welcome {
            get {
                return ResourceManager.GetString("SystemMessages_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN code wrong or was used already.
        /// </summary>
        internal static string SystemMessages_WrongOrUsedPIN {
            get {
                return ResourceManager.GetString("SystemMessages_WrongOrUsedPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your slot was closed.
        /// </summary>
        internal static string SystemMessages_YoursSlotClosed {
            get {
                return ResourceManager.GetString("SystemMessages_YoursSlotClosed", resourceCulture);
            }
        }
    }
}
